services:
  - docker

stages:
  - docker authentication
  - agent base container
  - agent tool containers

env: 
  global:
    - DOCKER_ORG=ustctt
    - DOCKER_REPO=ctt-agent
    - DOCKER_ORG_REPO="${DOCKER_ORG}/${DOCKER_REPO}"

jobs:
  include:
    - stage: docker authentication
      name: "Authenticate with Docker"
      script:
        - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
    - stage: docker base container
      name: "Build agent base container"
      env: 
        - TAG="${DOCKER_ORG_REPO}:base"
      script: 
        - docker build -t "${TAG}" test-tool-modules/
        - docker push "${TAG}"
    - stage: agent tool containers
      name: "Build agent tool container for JMeter"
      env:
        - TAG="${DOCKER_ORG_REPO}:jmeter"
      script:
        - docker build -t "${TAG}" test-tool-modules/jmeter/
        - docker push "${TAG}"
    - stage: agent tool containers
      name: "Build agent tool container for ApacheBench (ab)"
      env:
        - TAG="${DOCKER_ORG_REPO}:apachebench"
      script:
        - docker build -t "${TAG}" test-tool-modules/apachebench/
        - docker push "${TAG}"

