language: minimal

services:
  - docker

env:
  global:
    - DOCKER_ORG=ustctt
    - DOCKER_REPO=ctt-agent
    - DOCKER_ORG_REPO="${DOCKER_ORG}/${DOCKER_REPO}"

script:
  # Build CTT agent base container
  - docker build -t "${DOCKER_ORG_REPO}:base" test-tool-modules/
  # 
  # Build CTT agent JMeter container
  - docker build -t "${DOCKER_ORG_REPO}:jmeter" "test-tool-modules/jmeter/"
  #
  # Build CTT agent ApacheBench container
  - docker build -t "${DOCKER_ORG_REPO}:apachebench" "test-tool-modules/apachebench/"
  #
  #
  # DockerHub login
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
  #
  #
  # Push CTT agent base container to DockerHub
  - docker push "${DOCKER_ORG_REPO}:base"
  #
  # Push CTT agent JMeter container to DockerHub
  - docker push "${DOCKER_ORG_REPO}:jmeter"
  #
  # Push CTT agent ApacheBench container to DockerHub
  - docker push "${DOCKER_ORG_REPO}:apachebench"
  #
  #
  # DockerHub logout
  - docker logout
