language: minimal

services:
  - docker

env: 
  global:
    - DOCKER_ORG=ustctt
    - DOCKER_REPO=ctt-agent
    - DOCKER_ORG_REPO="${DOCKER_ORG}/${DOCKER_REPO}"

before_script:
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
  - docker build -t "${DOCKER_ORG_REPO}:base" test-tool-modules/
  - docker push "${DOCKER_ORG_REPO}:base"

script:
  - docker build -t "${DOCKER_ORG_REPO}:jmeter" test-tool-modules/jmeter/
  - docker build -t "${DOCKER_ORG_REPO}:apachebench" test-tool-modules/apachebench/

after_script:
  - docker push "${DOCKER_ORG_REPO}:jmeter"
  - docker push "${DOCKER_ORG_REPO}:apachebench"
